// End-to-end test for cactus::kokoro::KokoroModel.
//
// 1. Per-stage tests for the new BERT C++ port (validating against
//    bert_p<NN>_*.bin fixtures generated by kokoro_model_reference.py).
// 2. Top-level synthesize_with_phonemes against decoder_p<NN>_audio.bin.
// 3. Public synthesize(text) smoke test (only checks size + finiteness).

#include "test_utils.h"
#include "../cactus/models/kokoro/model.h"
#include "../cactus/models/kokoro/bert.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

// ----------------------------------------------------------------------
// Fixture helpers
// ----------------------------------------------------------------------
static std::string fixture_path(const std::string& name) {
    const char* env = std::getenv("CACTUS_TEST_FFT_FIXTURES");
    std::string base = env ? env : "../fixtures/data/";
    return base + name;
}

template <typename T>
static std::vector<T> load_typed(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) throw std::runtime_error("cannot open " + path);
    uint32_t n = 0;
    f.read(reinterpret_cast<char*>(&n), sizeof(n));
    std::vector<T> out(n);
    f.read(reinterpret_cast<char*>(out.data()), n * sizeof(T));
    if (!f) throw std::runtime_error("short read for " + path);
    return out;
}

static std::string find_weights_dir() {
    const char* candidates[] = {
        "assets/kokoro/weights",
        "../assets/kokoro/weights",
        "../../assets/kokoro/weights",
    };
    for (const char* p : candidates) {
        std::ifstream f(std::string(p) + "/bert_word_embeddings.weights");
        if (f) return p;
    }
    return "assets/kokoro/weights";
}

static std::string find_g2p_dict() {
    const char* candidates[] = {
        "assets/kokoro/kokoro-g2p.dict",
        "../assets/kokoro/kokoro-g2p.dict",
        "../../assets/kokoro/kokoro-g2p.dict",
    };
    for (const char* p : candidates) {
        std::ifstream f(p);
        if (f) return p;
    }
    return "assets/kokoro/kokoro-g2p.dict";
}

static std::string find_voice_path() {
    const char* candidates[] = {
        "tests/fixtures/data/voice_af_bella_raw.bin",
        "../fixtures/data/voice_af_bella_raw.bin",
        "../../tests/fixtures/data/voice_af_bella_raw.bin",
        "fixtures/data/voice_af_bella_raw.bin",
    };
    for (const char* p : candidates) {
        std::ifstream f(p, std::ios::binary);
        if (f) return p;
    }
    return "tests/fixtures/data/voice_af_bella_raw.bin";
}

static bool layer_close(const std::vector<float>& got,
                        const std::vector<float>& expected,
                        float abs_tol, float rel_tol, const char* label) {
    if (got.size() != expected.size()) {
        std::fprintf(stderr, "%s: SIZE MISMATCH got=%zu exp=%zu\n",
                     label, got.size(), expected.size());
        return false;
    }
    float max_abs = 0.0f, max_rel = 0.0f;
    int errors = 0;
    int n_violations = 0;
    for (size_t i = 0; i < got.size(); ++i) {
        const float d = std::fabs(got[i] - expected[i]);
        if (d > max_abs) max_abs = d;
        const float r = d / std::max(std::fabs(expected[i]), 1e-9f);
        if (r > max_rel) max_rel = r;
        const bool ok = (d <= abs_tol) || (r <= rel_tol);
        if (!ok) {
            ++n_violations;
            if (errors < 3) {
                std::fprintf(stderr, "%s: i=%zu got=%g exp=%g abs=%g rel=%g\n",
                             label, i, got[i], expected[i], d, r);
                ++errors;
            }
        }
    }
    const bool pass = (n_violations == 0);
    std::fprintf(stderr,
        "%s: max_abs=%.6g max_rel=%.6g (abs_tol=%.1g rel_tol=%.1g) %s\n",
        label, max_abs, max_rel, abs_tol, rel_tol,
        pass ? "PASS" : "FAIL");
    return pass;
}

// ----------------------------------------------------------------------
// Loaders for the model under test (BERT alone for stage tests, full
// KokoroModel for synthesis tests).
// ----------------------------------------------------------------------
static cactus::kokoro::Bert load_bert() {
    cactus::kokoro::Bert b;
    const auto dir = find_weights_dir();
    if (!b.load_weights(dir)) {
        throw std::runtime_error("Bert load_weights failed (dir=" + dir + ")");
    }
    return b;
}

static cactus::kokoro::KokoroModel load_kokoro() {
    cactus::kokoro::KokoroModel m;
    if (!m.load(find_weights_dir(), find_g2p_dict(), find_voice_path())) {
        throw std::runtime_error("KokoroModel::load failed");
    }
    return m;
}

// ----------------------------------------------------------------------
// BERT per-stage tests on p01.
//
// Per-stage tolerance: BERT runs 12 sequential ALBERT layers on mostly INT8
// weights (89 INT8 + 370 FP16 across the full model — see MANIFEST.json).
// Quantization noise compounds through the residual stack. Reference values
// in last_hidden span [-12, 2] (mean |x| = 0.32, std 0.59), so an absolute
// bound of 0.7 is ~6% of the dynamic range and consistent with the
// per-layer INT8 round-trip (~5e-2 max relative per the converter docs).
//
// What ultimately matters is whether the bert output produces correct
// downstream behavior: the strict synthesize_with_phonemes test (p04) and
// the BERT pooler test (which collapses the [CLS] hidden through a tanh
// to a 768-d vector that matches Python within 0.05 abs) are both green
// checks that the BERT pipeline is correct, with quantization the only
// source of error.
//
// Tolerance schedule: dual abs/rel — pass if EITHER bound is met.
//   abs 0.7  -> covers worst-case INT8 outliers in the 12-layer stack
//   rel 0.10 -> 10% on values |x|>0.05 (sub-threshold values are abs-bounded)
// ----------------------------------------------------------------------
static bool test_bert_last_hidden_p01() {
    auto b = load_bert();
    auto ids = load_typed<int64_t>(fixture_path("bert_p01_input_ids.bin"));
    const int T = static_cast<int>(ids.size());
    std::vector<float> got;
    b.forward(ids.data(), T, got);
    auto exp = load_typed<float>(fixture_path("bert_p01_last_hidden_state.bin"));
    return layer_close(got, exp, 0.7f, 0.10f, "bert_last_hidden_p01");
}

static bool test_bert_d_en_p01() {
    auto b = load_bert();
    auto ids = load_typed<int64_t>(fixture_path("bert_p01_input_ids.bin"));
    const int T = static_cast<int>(ids.size());
    std::vector<float> bert_dur;
    b.forward(ids.data(), T, bert_dur);
    std::vector<float> got;
    b.apply_bert_encoder(bert_dur.data(), T, got);
    auto exp = load_typed<float>(fixture_path("bert_p01_d_en.bin"));
    return layer_close(got, exp, 1.0f, 0.10f, "bert_d_en_p01");
}

static bool test_bert_pooled_p01() {
    auto b = load_bert();
    auto ids = load_typed<int64_t>(fixture_path("bert_p01_input_ids.bin"));
    const int T = static_cast<int>(ids.size());
    std::vector<float> bert_dur;
    b.forward(ids.data(), T, bert_dur);
    std::vector<float> got;
    b.apply_pooler(bert_dur.data(), T, got);
    auto exp = load_typed<float>(fixture_path("bert_p01_pooled_output.bin"));
    // pooled is tanh-squashed to (-1, 1). abs 5e-2 / rel 5e-2 — tighter
    // bound, since tanh saturates the worst INT8 outliers.
    return layer_close(got, exp, 5e-2f, 5e-2f, "bert_pooled_p01");
}

// ----------------------------------------------------------------------
// Top-level synthesize_with_phonemes test.
//
// Feed the misaki-derived phoneme IDs (already padded with [0, ..., 0]) from
// predictor_p<NN>_input_phonemes.bin. When the cactus predictor produces the
// same T_mel as the Python reference, inject decoder_p<NN>_har_source.bin to
// bypass SineGen PRNG and do a strict byte-comparable audio check vs
// decoder_p<NN>_audio.bin. When cactus T_mel deviates from Python (an
// off-by-one INT8 quantization round() flip in pred_dur — already documented
// in test_voice_predictor.cpp's e2e_all_phrases test), we fall back to a
// sanity check: the cactus pipeline must produce finite audio of the
// expected cactus length (600 * cactus_T_mel) with plausible amplitude.
//
// p04 hits the exact same rounding decisions as Python -> strict golden
// match. The other 4 phrases sit on the round() boundary for one or two
// phonemes, producing T_mel diffs of ±1-2.
// ----------------------------------------------------------------------
static bool test_synthesize_with_phonemes_one(const std::string& tag,
                                              float abs_tol, float rel_tol) {
    auto m = load_kokoro();
    auto ids = load_typed<int64_t>(fixture_path("predictor_" + tag + "_input_phonemes.bin"));
    auto har = load_typed<float>(fixture_path("decoder_" + tag + "_har_source.bin"));
    auto exp_audio = load_typed<float>(fixture_path("decoder_" + tag + "_audio.bin"));
    const int py_T_mel = static_cast<int>(har.size()) / 600;

    // First, run the cactus pipeline WITHOUT har_source to discover its T_mel
    // (cactus seed-driven path — produces audio of length 600 * cactus_T_mel).
    std::vector<float> audio_seeded;
    if (!m.synthesize_with_phonemes(ids.data(),
                                    static_cast<int>(ids.size()),
                                    audio_seeded,
                                    /*speed=*/1.0f,
                                    /*har_source=*/nullptr,
                                    /*har_len=*/0,
                                    /*seed=*/0)) {
        std::fprintf(stderr, "synthesize_with_phonemes %s seeded path failed\n", tag.c_str());
        return false;
    }
    const int cactus_T_mel = static_cast<int>(audio_seeded.size()) / 600;

    if (cactus_T_mel == py_T_mel) {
        // Exact-match path: re-run with injected har_source and check audio.
        std::vector<float> audio;
        if (!m.synthesize_with_phonemes(ids.data(),
                                        static_cast<int>(ids.size()),
                                        audio, 1.0f,
                                        har.data(),
                                        static_cast<int>(har.size()))) {
            std::fprintf(stderr, "synthesize_with_phonemes %s strict path failed\n", tag.c_str());
            return false;
        }
        char lab[64];
        std::snprintf(lab, sizeof(lab), "synth_phonemes_%s_STRICT", tag.c_str());
        return layer_close(audio, exp_audio, abs_tol, rel_tol, lab);
    }

    // T_mel mismatch (INT8 round() flip on duration). Fall back to a sanity
    // check on the seeded-PRNG run. We can't compare to fixture audio
    // (different length), but the audio MUST be finite, the expected length,
    // and have plausible amplitude.
    std::fprintf(stderr,
        "synth_phonemes_%s: cactus T_mel=%d != python T_mel=%d (INT8 round flip), "
        "running sanity check\n", tag.c_str(), cactus_T_mel, py_T_mel);
    if (static_cast<int>(audio_seeded.size()) != 600 * cactus_T_mel) {
        std::fprintf(stderr, "  audio length wrong: %zu (expected %d)\n",
                     audio_seeded.size(), 600 * cactus_T_mel);
        return false;
    }
    int n_finite = 0;
    float max_abs = 0.0f;
    for (float s : audio_seeded) {
        if (std::isfinite(s)) ++n_finite;
        const float a = std::fabs(s);
        if (a > max_abs) max_abs = a;
    }
    if (n_finite != static_cast<int>(audio_seeded.size())) {
        std::fprintf(stderr, "  found %d non-finite samples\n",
                     static_cast<int>(audio_seeded.size()) - n_finite);
        return false;
    }
    if (max_abs < 1e-3f || max_abs > 5.0f) {
        std::fprintf(stderr, "  amplitude out of range: max|s|=%.4f\n", max_abs);
        return false;
    }
    std::fprintf(stderr,
        "  sanity OK: %zu samples, max|s|=%.4f (T_mel diff=%+d)\n",
        audio_seeded.size(), max_abs, cactus_T_mel - py_T_mel);
    return true;
}

static bool test_synthesize_p01() {
    return test_synthesize_with_phonemes_one("p01", 5e-2f, 1e-1f);
}
static bool test_synthesize_p02() {
    return test_synthesize_with_phonemes_one("p02", 5e-2f, 1e-1f);
}
static bool test_synthesize_p03() {
    return test_synthesize_with_phonemes_one("p03", 5e-2f, 1e-1f);
}
static bool test_synthesize_p04() {
    return test_synthesize_with_phonemes_one("p04", 5e-2f, 1e-1f);
}
static bool test_synthesize_p05() {
    return test_synthesize_with_phonemes_one("p05", 5e-2f, 1e-1f);
}

// ----------------------------------------------------------------------
// Public synthesize(text) smoke test. ARPAbet (CMUdict) phonemes don't
// match misaki IPA exactly, so we can't byte-compare — just verify a
// non-empty PCM stream of plausible amplitude is produced.
// ----------------------------------------------------------------------
static bool test_synthesize_text_smoke() {
    auto m = load_kokoro();
    std::vector<float> audio;
    bool ok = m.synthesize("Hello world.", 1.0f, audio, /*seed=*/42);
    if (!ok) {
        std::fprintf(stderr, "synthesize(text) returned false\n");
        return false;
    }
    if (audio.size() < 1000) {
        std::fprintf(stderr, "synthesize(text) audio too short: %zu samples\n",
                     audio.size());
        return false;
    }
    int n_finite = 0;
    float max_abs = 0.0f;
    for (float s : audio) {
        if (std::isfinite(s)) ++n_finite;
        const float a = std::fabs(s);
        if (a > max_abs) max_abs = a;
    }
    std::fprintf(stderr,
        "synth_text: %zu samples, %d finite, max|s|=%.4f\n",
        audio.size(), n_finite, max_abs);
    if (n_finite != static_cast<int>(audio.size())) return false;
    if (max_abs > 5.0f || max_abs < 1e-4f) return false;
    return true;
}

// ----------------------------------------------------------------------
int main() {
    TestUtils::TestRunner runner("cactus::kokoro::KokoroModel");
    try {
        runner.run_test("BERT last_hidden_state (p01)", test_bert_last_hidden_p01());
        runner.run_test("BERT d_en (bert_encoder, p01)", test_bert_d_en_p01());
        runner.run_test("BERT pooler (p01)",            test_bert_pooled_p01());
        runner.run_test("synthesize_with_phonemes p01", test_synthesize_p01());
        runner.run_test("synthesize_with_phonemes p02", test_synthesize_p02());
        runner.run_test("synthesize_with_phonemes p03", test_synthesize_p03());
        runner.run_test("synthesize_with_phonemes p04", test_synthesize_p04());
        runner.run_test("synthesize_with_phonemes p05", test_synthesize_p05());
        runner.run_test("synthesize(text) smoke",       test_synthesize_text_smoke());
    } catch (const std::exception& e) {
        std::fprintf(stderr, "Test threw: %s\n", e.what());
        runner.run_test("Test threw exception", false);
    }
    runner.print_summary();
    return runner.all_passed() ? 0 : 1;
}
